sudo: false
language: node_js
node_js: v4

env:
  - COMPOSE_VERSION=1.8.1 DOCKER_CLIENT_TIMEOUT=1000 NODE_ENV=test

services:
  - docker

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose

script: ./docker-compose run -e NODE_ENV api 'npm test'

notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: never
  email: false
