api:
   build: ./
   command: node api/api.js
   links:
      - db
      - broker
   ports:
      - "9001:9001"
   environment:
      - VIRTUAL_HOST=pheromon-alpha.ants.builders
      - VIRTUAL_PORT=9001
      - BROKER_PORT=9901
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=elements
      - PGPASSWORD=elements
      - NODE_ENV=alpha
      # Updater variables
      - UPDATER_RANGE_START=2200
      - UPDATER_RANGE_SIZE=10
      - UPDATER_PLAYBOOK_FOLDER=/pheromon/updateFiles/
      - UPDATER_SENSORS_PORT=22
      - NODE_TLS_REJECT_UNAUTHORIZED=0

   volumes:
      - ./:/pheromon
      # Ansible playbooks for the updater
      - ./updateFiles/:/pheromon/updateFiles/:ro
      # SSH configuration
      - /home/sensorSSH/.ssh/id_rsa:/root/.ssh/id_rsa:ro
      - /home/sensorSSH/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub:ro
      - /home/sensorSSH/.ssh/known_hosts:/root/.ssh/known_hosts
      # Database backups
      - /data/pheromon-alpha/backups:/backups/
   tty: true
   restart: always

broker:
   build: .
   command: node broker/index.js
   links:
      - db
      - redis
   ports:
      - "9901:9901"
   environment:
      - BROKER_PORT=9901
      - NODE_ENV=alpha
   volumes:
      - ./:/pheromon
   tty: true
   restart: always

db:
   image: postgres:9.4
   environment:
      - NODE_ENV=alpha
   volumes:
      - /data/pheromon-alpha/db:/var/lib/postgresql/data
   tty: true
   restart: always

redis:
   image: redis:3
   restart: always
