pheromon:
   build: .
   command: node tools/init-db
   links:
      - db
   environment:
      - POSTGRES_USER=postgres
      - PGPASSWORD=elements
      - POSTGRES_PASSWORD=elements
   volumes:
      - ./:/pheromon/
   tty: true

db:
   image: postgres:9.4
   environment:
      - POSTGRES_USER=postgres
      - PGPASSWORD=elements
      - POSTGRES_PASSWORD=elements
   volumes:
      - ./data:/var/lib/postgresql
   tty: true