---
- hosts: all
  remote_user: root
  tasks:
  - name: get the new version of 6brain
    git:
      repo: https://github.com/anthill/6brain.git
      dest: "/home/pi/6brain"
      update: yes
      version: master

  - name: update 6brain
    npm:
      path: "/home/pi/6brain"

  - name: update 6bin
    npm:
      name: 6bin
      path: "/home/pi/6brain"
      version: "1.3.2"

  - name: update waste-categories
    npm:
      name: waste-categories
      path: "/home/pi/6brain"
      version: "1.1.1"
